### ISSUE TITLE
这么不更新啦？

### ISSUE THREAD

**Issue by ghost** [Eatzhy/surface-defect-detection#2]

**Comment by henbucuoshanghai** [comment]
最新的有吗？工业瑕疵检测？

**Comment by sky-fly97** [comment]
> 最新的有吗？工业瑕疵检测？

求推荐~

**Comment by DLwyp** [comment]
博主应该工作了吧

**Comment by Eatzhy** [comment]
@jinge1001 @DLwyp @sky-fly97 @henbucuoshanghai 谢谢关注，因为工作了很少关注工业检测，但是最近跳槽换工作，抽空把近期的论文过了一遍，国庆前会更新一些这两年比较好的paper。

**Comment by tomatowithpotato** [comment]
感谢作者的无私奉献
缺陷检测领域有哪些期刊和会议啊？小白求赐教
